name: Build

env:
  OS_TARGET: 'ubuntu-latest'

on:
  pull_request:
    # paths-ignore:
    #   - '**.md'
    branches:
      - releases/*
  push:
    branches:
      # - main
      - releases/*
    # paths-ignore:
    #   - '**.md'

jobs:
  install:
    runs-on: ${{ env.OS_TARGET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn install
  build:
    needs: [install]
    runs-on: ${{ env.OS_TARGET }}
    steps:
      - run: yarn build