name: Build

on:
  pull_request:
    # paths-ignore:
    #   - '**.md'
    branches:
      - releases/*
  push:
    branches:
      # - main
      - releases/*
    # paths-ignore:
    #   - '**.md'

jobs:
  nodejs-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Build service
        run: yarn build