name: install

on:
  pull_request:
    # paths-ignore:
    #   - '**.md'  
    branches:  
      - releases/*
  push:
    branches:
      # - main
      - releases/*
    # paths-ignore:
    #   - '**.md'

jobs:
  node-yarn-depencies-caching:
    name: Yarn (Node v14.18.1, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install